
name: Deployment To AWS EC2
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
concurrency:
  group: build-and-test
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: docker build -t spm:'${{github.sha}}' .

      - name: docker login
        run: docker login --username '${{secrets.DOCKER_USERNAME}}' --password '${{secrets.DOCKER_PASSWORD}}'

      - name: tag docker image
        run: docker tag spm:'${{github.sha}}' '${{secrets.DOCKER_USERNAME}}'/spm:'${{github.sha}}'

      - name: push docker image
        run: docker push '${{secrets.DOCKER_USERNAME}}'/spm:'${{github.sha}}'

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
  #   - name: SSH deploy
  #     uses: appleboy/ssh-action@v0.1.4
  #     with:
  #        host: ${{ secrets.HOSTNAME  }}
  #        username: ${{ secrets.USER_NAME  }}
  #        key:  ${{ secrets.AWS_PRIVATE_KEY  }}
  #        passphrase: ${{ secrets.PASSPHASE }}
  #        port:  ${{ secrets.PORT }}
  #        script: whoami
  
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: sudo whoami
        host: ${{ secrets.HOSTNAME  }}
        user: ${{ secrets.USER_NAME  }}
        key: ${{ secrets.AWS_PRIVATE_KEY  }}
        pass: ${{ secrets.PASSPHASE }}
