
name: Deployment
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: docker build -t spm:'${{github.sha}}' .

      - name: docker login
        run: docker login --username '${{secrets.DOCKER_USERNAME}}' --password '${{secrets.DOCKER_PASSWORD}}'

      - name: tag docker image
        run: docker tag spm:'${{github.sha}}' '${{secrets.DOCKER_USERNAME}}'/spm:'${{github.sha}}'

      - name: push docker image
        run: docker push '${{secrets.DOCKER_USERNAME}}'/spm:'${{github.sha}}'

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
          sudo echo "$PRIVATE_KEY" > spm-backend-key.pem && chmod 600 spm-backend-key.pem
          sudo find . -iname spm-backend-key.pem
          sudo pwd
          ssh -o StrictHostKeyChecking=no -T ./spm-backend-key.pem '${USER_NAME}'@$'{HOSTNAME}'
          docker login --username '${{secrets.DOCKER_USERNAME}}' --password '${{secrets.DOCKER_PASSWORD}}'
          docker run -p 8001:8001 '${{secrets.DOCKER_USERNAME}}'/spm:'${{github.sha}}'
          
          
